function [param_str,params] = extract_params(T)
%function takes in a many variable table (ony one row) and returns those
%variables that are parameters of the model. 

params_str = {};
params = [];

T_list = T.Properties.VariableNames;

if ismember('Tre', T_list)
    p_list = {'Tre','Tde','Ae','mue','sige',...
              'Tri','Tdi','Ai','mui','sigi',...
              'Tre2','Tde2','Ae2','mue2','sige2',...
              'Taut'};
elseif ismember('TiPC', T_list) && ismember('dE', T_list)
    p_list = {'muE', 'muI', 'muE2', 'muI2', 'sigE', 'sigI', 'sigE2', 'sigI2', 'AE', 'AI','AE2', ...
              'AI2', 'TrE', 'TrI', 'TrE2', 'TrI2', 'TdE', 'TdI','TdE2', 'TdI2', ...
              'dE', 'dI', 'dE2', 'dI2', 'TiPC', 'TiNC'};
    
elseif ismember('TiPC', T_list) && ismember('h40E', T_list)
    p_list = {'muE', 'muI', 'muE2', 'muI2', 'sigE', 'sigI', 'sigE2', 'sigI2', 'APCE', 'APCI','APCE2', ...
              'APCI2', 'ANCE', 'ANCI', 'ANCE2', 'ANCI2', 'TrE', 'TrI', 'TrE2', 'TrI2', 'TdE', 'TdI', ...
              'TdE2', 'TdI2', ...
              'h40E', 'h40I', 'h40E2', 'h40I2', 'h80E', 'h80I', 'h80E2', 'h80I2', ...
              'h160E', 'h160I', 'h160E2', 'h160I2', 'h320E', 'h320I', 'h320E2', 'h320I2', 'h640E', ...
              'h640I', 'h640E2', 'h640I2', ...
              'TtE', 'TtI', 'TtE2', 'TtI2', 'TiPC', 'TiNC'};
elseif ismember('TiPC', T_list) && ismember('b40E', T_list)
    if ismember('APCE', T_list) 
        p_list = {'muE', 'muI', 'muE2', 'muI2', 'sigE', 'sigI', 'sigE2', 'sigI2', 'APCE', 'APCI','APCE2', ...
                  'APCI2', 'ANCE', 'ANCI', 'ANCE2', 'ANCI2', 'TrE', 'TrI', 'TrE2', 'TrI2', 'TdE', 'TdI', ...
                  'TdE2', 'TdI2', ...
                  'b40E', 'b40I', 'b40E2', 'b40I2', 'b80E', 'b80I', 'b80E2', 'b80I2', ...
                  'b160E', 'b160I', 'b160E2', 'b160I2', 'b320E', 'b320I', 'b320E2', 'b320I2', 'b640E', ...
                  'b640I', 'b640E2', 'b640I2', ...
                  'TtE', 'TtI', 'TtE2', 'TtI2', 'TiPC', 'TiNC'};
    elseif ismember('AE', T_list) 
        p_list = {'muE', 'muI', 'muE2', 'muI2', 'sigE', 'sigI', 'sigE2', 'sigI2', 'AE', 'AI','AE2', ...
                  'AI2', 'TrE', 'TrI', 'TrE2', 'TrI2', 'TdE', 'TdI', ...
                  'TdE2', 'TdI2', ...
                  'b40E', 'b40I', 'b40E2', 'b40I2', 'b80E', 'b80I', 'b80E2', 'b80I2', ...
                  'b160E', 'b160I', 'b160E2', 'b160I2', 'b320E', 'b320I', 'b320E2', 'b320I2', 'b640E', ...
                  'b640I', 'b640E2', 'b640I2', ...
                  'TtE', 'TtI', 'TtE2', 'TtI2', 'TiPC', 'TiNC'};
    end

elseif ismember('TiPC', T_list)
    p_list = {'muE', 'muI', 'muE2', 'muI2', 'sigE', 'sigI', 'sigE2', 'sigI2', 'APCE', 'APCI','APCE2', ...
              'APCI2', 'ANCE', 'ANCI', 'ANCE2', 'ANCI2', 'TrE', 'TrI', 'TrE2', 'TrI2', 'TdE', 'TdI', ...
              'TdE2', 'TdI2', 'TtE', 'TtI', 'TtE2', 'TtI2', 'TiPC', 'TiNC'};
else
    p_list = {'muE', 'muI','muE2', 'muI2', 'sigE', 'sigI', 'sigE2', 'sigI2', 'APCE', ...
          'APCI', 'APCE2', 'APCI2', 'ANCE', 'ANCI', 'ANCE2', 'ANCI2', 'TrPCE', 'TrPCI', ...
          'TrPCE2', 'TrPCI2', 'TdPCE', 'TdPCI', 'TdPCE2', 'TdPCI2', 'TrNCE', 'TrNCI', ...
          'TrNCE2', 'TrNCI2', 'TdNCE', 'TdNCI', 'TdNCE2', 'TdNCI2', 'TtE', 'TtI', 'TtE2', 'TtI2'};        
end

          
counter = 1;
for i = 1:length(p_list)
    var_idx = strcmp(T_list,p_list{i});
    if ~any(var_idx)
        continue
    end
    param_str{counter} = T_list{var_idx};
    params = [params,T{:,var_idx}];
    counter = counter+1;
end
        