function xPos = extractPositionFromTDMSStruct(tdmsStruct)

% function xPos = extractPositionFromTDMSStruct(tdmsStruct)
%
% This function exctracts the x position from the TDMS command data. 
% Strongly depends on the TDMS structure and focuses only on dump frame
% commands
%
% INPUT
% tdmsStruct -  generated by reading log file with TDMS_readTDMSFile
%
% OUTPUT
% xPos -        X position as reported by dump frame

groupInd  = find(cellfun(@(x) strcmp(x, 'Pattern Position'), tdmsStruct.groupNames));


nameInd = find(cellfun(@(x) strcmp(x, 'X Index'), tdmsStruct.chanNames{groupInd}));
timeInd = find(cellfun(@(x) strcmp(x, 'Time'), tdmsStruct.chanNames{groupInd}));

posNumInd = tdmsStruct.chanIndices{groupInd}(nameInd);
timeStInd = tdmsStruct.chanIndices{groupInd}(timeInd);


posNum = tdmsStruct.data{posNumInd};
timeStamp = tdmsStruct.data{timeStInd};
xPos = [timeStamp', double(posNum')];

    


end