function inputDat = extractAnaDataFromTDMSStruct(tdmsStruct, type)

% function xPos = extractAnaDataFromTDMSStruct(tdmsStruct)
%
% This function exctracts the analog data from the TDMS file. 
% Strongly depends on the TDMS structure and focuses only. 
% Function can be modified to take time stamps from all channels (if
% smapling rate is different)
%
% INPUT
% tdmsStruct -  generated by reading log file with TDMS_readTDMSFile
% type -        String. Type of data to be extracted. Options are
%   ADC:        Analog input channel (recorded)
%   AO:         Analog output channel (recorded)
%
% OUTPUT
% inputDat -    recorded voltage and time stamp (only from one channel) from all the ADC# channels

assert(ischar(type), 'Type should be "ADC" or "AO" only')
type = upper(type);
assert(ismember(type, {'ADC', 'AO'}), 'Type should be "ADC" or "AO" only')

relGroups  = cellfun(@(x) strfind(x, type), tdmsStruct.groupNames, 'uniformoutput', 0);
groupInd = find(cellfun(@(x) ~isempty(x), relGroups));

% Making sure channels are read in in the correct order (by name)
adcGroupNames = vertcat(tdmsStruct.groupNames{groupInd});
[~, ord] = sort(adcGroupNames(:,end));
groupInd = groupInd(ord);

% assumes equal sampling rate on all channels 
baseInd = tdmsStruct.chanIndices{groupInd(1)}(1); % just to get the size of the group (does matter which member)
numSamp = tdmsStruct.numberDataPointsRaw(baseInd);
inputDat = zeros(numSamp, length(groupInd)+1);

for ii=1:length(groupInd)
    
    if ii==1
        timeInd = find(cellfun(@(x) strcmp(x, 'Time'), tdmsStruct.chanNames{groupInd(ii)}));
        timeStInd = tdmsStruct.chanIndices{groupInd(ii)}(timeInd);
        timeStamp = tdmsStruct.data{timeStInd};
        inputDat(:, ii) = timeStamp;
    end
    
    chanInd = find(cellfun(@(x) strcmp(x, 'Voltage'), tdmsStruct.chanNames{groupInd(ii)}));
    dataInd = tdmsStruct.chanIndices{groupInd(ii)}(chanInd);
    vData = tdmsStruct.data{dataInd};
    inputDat(:, ii+1) = vData;
    

end
    


end