function allResultSt = applyFunctionOnT4dataset(t4CellStruct, relProtName, funcHand)

% function applyFunctionOnT4dataset(t4CellStruct, relProtName, funcHand)
%
% This function applies the same procedure on all the protocols in the T$
% dataset. 
%
% INPUT
%
% t4CellStruct -                structure with file name generated by
%                               assingingProtocols2CellsScript
%
% relProtName -                 protocol name that the function will be
%                               applied on (from the fields of the above structue)
%
% funcHand -                    function handle to be applied on relevant
%                               protocol
%
% OUTPUT
% allResultSt -                 Depends on the applied function. but
%                               organized in a structure the same size as t4CellStruct
%
% NOTE!! function should be run from the directory containing all the T4
% recordings

clear protocolStruct

allFields = fieldnames(t4CellStruct);

assert(ismember(relProtName, allFields), 'relProtName does not appear in t4CellStruct fields')

numCells = length(t4CellStruct);

allResultSt = struct;

for ii=1:numCells
    
    relDir = t4CellStruct(ii).dir;
    relField = getfield(t4CellStruct(ii), relProtName);
    
    if ~isempty(relField)
        
        numProts = length(relField);
        
        if isfield(relField, 'correct') % in case I already labeled the relevant protocol
            for jj=1:numProts
                relProt(jj) =  ~isempty(relField(jj).correct);
                relProt = find(relProt);
            end
        else
            relProt = 1:numProts;
        end
        
        tempResCell = cell(1, length(relProt));
        
        for jj=1:length(relProt)
            
            load(fullfile(pwd, relDir, relField(relProt(jj)).fileName))
            
            tempRes = feval(funcHand, protocolStruct);
            
            tempResCell{jj} = tempRes;
        end
        
        allResultSt(ii).result = tempResCell;
        
        clear protocolStruct
        
    end
    
    fprintf('finished cell %d of %d \n', ii, numCells)
       
end




end
