function varargout = plotRFsFromSevralProt(relProts, expRes, expSt, relFreq, patternsDir)

% function plotRFfromProtocol(relProt, expRes, expSt, relFreq, patternsDir)
%
% This function uses plotRFfromProtocol to plot the RFs of several
% protocols and then sum them together for lihgt and dark pixels
% seperately. 
%
% INPUT
%
% relProts -        Array of protocal numbers from expSt
% expRes -          expResults structure generated by runPanelExperiment (has
%                   protocolNum and dara fields)
% expSt -           expStructure generated by checkExpStruct (has pattern, posFun,
%                   and protocol fields)
% relFreq -         freqeuncy with which pattern was played (recorded in
%                   expProts)
% patternsDir -     directory of relevant pattern files
%
% OUTPUT (optional)
%
% output{1} =       data to generate final plot


allRFs = cell(1, length(relProts));
plotNorm = zeros(length(relProts), 2);

for ii=1:length(relProts)
    
    [allRFs{ii}, fh] = plotRFfromProtocol(relProts(ii), expRes, expSt, relFreq, patternsDir);
    
    % provides time to peruse the figure
    disp('Press any key to continue')
    inp = waitforbuttonpress;
    while inp~=1
        inp = waitforbuttonpress;
    end
    
    plotNorm(ii, :) = fh~= 0;
    
    for jj=1:2
        if fh(jj) ~= 0
            close(fh(jj))
        end
    end
    
    
end

plotNorm = sum(plotNorm);

combRFL = zeros(size(allRFs{1}, 1), size(allRFs{1},2));
combRFD = combRFL;

for ii=1:length(relProts)
    combRFL = combRFL + allRFs{ii}(:,:,1);
    combRFD = combRFD + allRFs{ii}(:,:,2);
end

combRFL = combRFL/plotNorm(1);
combRFD = combRFD/plotNorm(2);

totmax = max([max(combRFL(:)), max(combRFD(:))]);

figure( 'units', 'normalized', 'position', [0.3, 0.45, 0.45, 0.25]);
cmap = colormap('hot');
imagesc(combRFL, [0, totmax]);
axis equal
colormap(flipud(cmap))
set(gca, 'xlim', [0.5, size(combRFL, 2)], 'ylim', [0.5, size(combRFL, 1)], ...
    'xtick', [], 'ytick', [])
hold on
    % adds red lines
for ii=0.5:8:size(combRFL, 2)
    line([ii, ii], [0, size(combRFL, 1)], 'color', 'r', 'linewidth', 1)
end

for ii=0.5:8:size(combRFL, 1)
    line([0, size(combRFL, 2)], [ii, ii], 'color', 'r', 'linewidth', 1)
end
hold off
    
colorbar('location', 'southoutside')


figure('units', 'normalized', 'position', [0.3, 0.2, 0.45, 0.25]);
cmap = colormap('hot');
imagesc(combRFD, [0, totmax]);
axis equal
colormap(rot90(cmap,2))
set(gca, 'xlim', [0.5, size(combRFD, 2)], 'ylim', [0.5, size(combRFD, 1)], ...
    'xtick', [], 'ytick', [])
hold on
    % adds red lines
for ii=0.5:8:size(combRFD, 2)
    line([ii, ii], [0, size(combRFD, 1)], 'color', 'r', 'linewidth', 1)
end

for ii=0.5:8:size(combRFD, 1)
    line([0, size(combRFD, 2)], [ii, ii], 'color', 'r', 'linewidth', 1)
end
hold off

colorbar('location', 'southoutside')


if nargout == 1
    varargout{1} = {combRFL; combRFD};
end
    



end





