function playStimByIndwImplay(pStruct, stimInd)

% function playStimByIndwImplay(pStruct, stimInd)
%
% this function uses playStimwImplay but uses protocolStruct and stimInd as
% direct inputs 
%
% INPUTS 
% pStruct -     protocolStruct generated by one of the createXXXProtocol
%               functions
% stimInd -     Index from the corresponding gratingTable field in
%               protocolStruct

if length(stimInd) == 1
    temp = getStimInds(pStruct, [stimInd, nan, 1,1]);
elseif length(stimInd) == 4
    temp = getStimInds(pStruct, stimInd);
end

assert(length(temp) == 1, 'stimInd produced more than one result')

tempInd = temp.inds(1);

tempStimSeq = pStruct.stim(tempInd).matCell;

playStimwImplay(tempStimSeq)




end